-- DROP TABLE [RSVP]
-- DROP TABLE Dinners

-- CREATE DATABASE NerdDinner
-- GO

USE NerdDinner

CREATE TABLE [dbo].[Dinners](
	[DinnerID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[EventDate] [datetime] NOT NULL,
	[Description] [nvarchar](256) NOT NULL,
	[HostedBy] [nvarchar](20) NOT NULL,
	[ContactPhone] [nvarchar](20) NOT NULL,
	[Address] [nvarchar](50) NOT NULL,
	[Country] [nvarchar](30) NOT NULL,
	[Latitude] [float] NOT NULL,
	[Longitude] [float] NOT NULL,
 CONSTRAINT [PK_Dinners] PRIMARY KEY CLUSTERED ([DinnerID] ASC)
);

CREATE TABLE [dbo].[RSVP](
	[RsvpID] [int] IDENTITY(1,1) NOT NULL,
	[DinnerID] [int] NOT NULL,
	[AttendeeName] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_RSVP] PRIMARY KEY CLUSTERED ([RsvpID] ASC)
);

ALTER TABLE [dbo].[RSVP]  WITH CHECK ADD  CONSTRAINT [FK_RSVP_Dinners] FOREIGN KEY([DinnerID])
REFERENCES [dbo].[Dinners] ([DinnerID]);

-- INSERTs generated by 'sp_generate_inserts' stored procedure written by Vyas
-- Build number: 22
-- Problems/Suggestions? Contact Vyas @ vyaskn@hotmail.com
-- http://vyaskn.tripod.com

--  note that date values were moved forward from 2009 to 2015.  this saves problems later working through the tutorial, but be aware.
INSERT INTO [Dinners] ([Title],[EventDate],[Description],[HostedBy],[ContactPhone],[Address],[Country],[Latitude],[Longitude])VALUES('.NET Futures','Dec  6 2015  5:00:00:000PM','Come talk about cool things coming with .NET','scottgu','425-555-1212','One Microsoft Way, Redmond WA','USA',4.764312000000000e+001,-1.221306090000000e+002);
INSERT INTO [Dinners] ([Title],[EventDate],[Description],[HostedBy],[ContactPhone],[Address],[Country],[Latitude],[Longitude])VALUES('Geek Out','Dec  6 2015 12:00:00:000AM','All things geek allowed','scottha','425-555-1212','One Microsoft Way, Redmond WA','USA',4.764312000000000e+001,-1.221306090000000e+002);
INSERT INTO [Dinners] ([Title],[EventDate],[Description],[HostedBy],[ContactPhone],[Address],[Country],[Latitude],[Longitude])VALUES('Fine Wine','Dec  7 2015 12:00:00:000AM','Sample some fine Washington Wine','philha','425-555-1212','One Microsoft Way, Redmond WA','USA',4.763254600000000e+001,-1.222120100000000e+002);
INSERT INTO [Dinners] ([Title],[EventDate],[Description],[HostedBy],[ContactPhone],[Address],[Country],[Latitude],[Longitude])VALUES('Surfing Lessons','Dec  8 2015 12:00:00:000AM','Ride the waves with Rob','robcon','425-555-1212','One Microsoft Way, Redmond WA','USA',4.763254600000000e+001,-1.222120100000000e+002);
INSERT INTO [Dinners] ([Title],[EventDate],[Description],[HostedBy],[ContactPhone],[Address],[Country],[Latitude],[Longitude])VALUES('Curing Polio','Dec  9 2015 12:00:00:000AM','Discuss how we can eradicate polio around the world','billg','425-555-1212','One Microsoft Way, Redmond WA','USA',4.763254600000000e+001,-1.222120100000000e+002);
INSERT INTO [Dinners] ([Title],[EventDate],[Description],[HostedBy],[ContactPhone],[Address],[Country],[Latitude],[Longitude])VALUES('Dinner with Sus','Feb 28 2015  5:00:00:000PM','Fun dinner with the wife','scottgu','425-555-1212','One Microsoft Way, Redmond WA','USA',4.763254600000000e+001,-1.222120100000000e+002);
INSERT INTO [Dinners] ([Title],[EventDate],[Description],[HostedBy],[ContactPhone],[Address],[Country],[Latitude],[Longitude])VALUES('XBOX Gaming','Mar  1 2015  5:00:00:000PM','Game Fest with the newest XBox Games!','scottgu','425-555-1212','One Microsoft Way, Redmond WA 98052','USA',4.764312000000000e+001,-1.221306090000000e+002);
